[package]
name = "loadavg_gui"
version = "0.1.0"
authors = ["hibi221b"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
